### ISSUE TITLE
Wrong banner and forum topic on blog article

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra-web#9]
Broken article: https://citra-emu.org/entry/texture-forwarding-brings-hd-output-to-citra/

This currently links to https://community.citra-emu.org/t/no-sound-in-windows-10/190/5 (which was closed after 30 days by "System" [which probably shouldn't happen - at least not for news articles imo]).

Also the header is squished currently (not sure if this is a temporary issue / why?)

**Comment by chris062689** [comment]
This is just a matter of the wrong forum topic being associated with the entry. 

The system autoclose was some testing we were doing that just happened to overlap this issue. 

The header appears squished due to the length of the title, working as expected.

**Comment by JayFoxRox** [comment]
Also links to both authors profiles are dead.

**Comment by chris062689** [comment]
Believe this has been resolved. Can you confirm @JayFoxRox?

**Comment by JayFoxRox** [comment]
Partially resolved. The forum link is fine now.


## Header still squished

![Header](http://i.imgur.com/lG4UWlM.png)

=  don't tell me it's intended.. if it is we should change the intention.

## User profiles have bad avatar and link

![users](http://i.imgur.com/VXYJwH6.png)
![jmc bad](http://i.imgur.com/6fWqiyM.png)

= We should link to dummy profiles or not link altogether if they don't have an account yet?
As an avatar we should use placeholder [questionmark or at least something which suggests that it's an unknown author]

**Comment by chris062689** [comment]
@bunnei can you review the header? It may just be the incorrect size. 

I agree linking to a profile that doesn't exist is a bug, and will look into fixing that.

**Comment by chris062689** [comment]
What is the status of this issue @JayFoxRox? It's not clear from the description.

**Comment by JayFoxRox** [comment]
The user profile links are still bad:

> Written by JMC47 and tfarley on Sunday May 01, 2016

Clicking on their names sends you to "Oops! That page doesn’t exist or is private."
They also [both have this avatar](https://community.citra-emu.org/user_avatar/community.citra-emu.org/citrabot/120/28_1.png). Therefore:

> = We should link to dummy profiles or not link altogether if they don't have an account yet?
As an avatar we should use placeholder [questionmark or at least something which suggests that it's an unknown author]

This (detecting missing accounts) should be fixed in the blog-code. We might have more articles by people who don't have a forum account or where the forum account will be removed over time.

---

The header image looks fine now, It's not looking good either though - it's heavily cropped, blurry and contains the HUD ("1st") in the upper right. The banner also does not contain the citra logo + text like most other articles.

This does not have to be fixed as it's an old post. We should just use proper banners for new articles for new posts.

*I also still think we should not embedd the Citra logo and header / title in the image. They should be overlaid by the blog system. That way it would be easier to change titles / create new posts. Also if we ever change the blog design / style, we could re-use the old titles more easily.
However, that's a seperate issue*
